### ISSUE TITLE
Create CW20 contract page

### ISSUE THREAD

**Issue by grikomsn** [CosmosContracts/juno-tools#100]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/8220954/158257849-51311a77-32d5-45c4-941f-a3c27bafde64.png">

<img width="940" alt="image" src="https://user-images.githubusercontent.com/8220954/158257915-1431c7b9-a0e4-4920-863d-eb885fb7f25f.png">

**Comment by grikomsn** [comment]
@RyanWarner you can update the parent comment if there are any mockup updates 👋🏻

**Comment by findolor** [comment]
@grikomsn 

With the current instantiate implementation `initial_balances` only has one element which is the user address. This needs to be a list of addresses and amounts. User needs to enter any amount of these pairs and it should reflect the list on the form.

With the current query implementation some of the queries take an address value. For now we are using the user's address but we should be able to use any address in those queries. Based on the query one or two additional text inputs needs to be visible in the form.

I'll look into the query forms but for the initial_balances list, we need a good way to display it to user.

**Comment by findolor** [comment]
Query text inputs done in #131

**Comment by findolor** [comment]
Hey @grikomsn there is also this initial balances issue that we haven't done https://github.com/CosmosContracts/juno-tools/issues/100#issuecomment-1091330601
Do you have anything in mind about how it might look?

**Comment by grikomsn** [comment]
Will try to design this today! cc @RyanWarner
