### ISSUE TITLE
Extension not available error

### ISSUE THREAD

**Issue by findolor** [CosmosContracts/juno-tools#156]
When refreshing the page multiple times we get ```Keplr extension is not available error```. After a while it connects normally.

**Comment by findolor** [comment]
@grikomsn It wasn't connecting slow before, any idea why this is happening?

**Comment by grikomsn** [comment]
@findolor is there any reproduction steps? On my end it behaves properly.

**Comment by findolor** [comment]
@grikomsn  So what I do is open the website and refresh the page a couple of times. Sometimes it happens on the first and sometimes the third time but eventually it doesn't connect. Here is a gif

![recording](https://user-images.githubusercontent.com/16416963/165604783-981bd247-93f2-4cae-8b30-c35c86d3d106.gif)

**Comment by grikomsn** [comment]
I'm assuming it depends on the browser and extensions installed. I'll debug further.
