### ISSUE TITLE
Descriptions for execute messages

### ISSUE THREAD

**Issue by RyanWarner** [CosmosContracts/juno-tools#157]
These are from @findolor, sent via Discord. Copy pasting here for easy access.

- Send
  Move some amount of tokens from one address to another address and execute a message in the end.

- Transfer
  Move some amount of tokens from one address to another address.

- Burn
  Remove some amount of tokens from the balance of an address and reduce total token supply by the same amount.

- Increase Allowance
  Increase the allowance of an address based on your balance. This is basically delegating your balance to another address.

- Decrease Allowance
  Decrease the allowance of an address based on your balance.

- Send From
  Make use of an allowance and move some amount of tokens from one address to another address and execute a message in the end.

- Transfer From
  Make use of an allowance and move some amount of tokens from one address to another address.

- Burn From
  Make use of an allowance and remove some amount of tokens from the balance of owner's address.

- Update Marketing
  Update marketing info object.

- Update Logo
  Update token logo url.

**Comment by grikomsn** [comment]
![](https://media.discordapp.net/attachments/933515307597848656/969367469246517309/CleanShot_2022-04-29_at_05.38.23.gif)
