### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by plsgiveup** [CosmosContracts/juno-tools#16]
On Night Theme- JunoTools text and Airdrops button frame is evident
![image](https://user-images.githubusercontent.com/88271672/153503289-4a2e1fe7-c7e6-4fbe-923b-e3d96d656302.png)

On Light Theme- They're not evident
![image](https://user-images.githubusercontent.com/88271672/153503597-5dab6606-7a82-4a8a-8c3c-9adaea78f8fb.png)

On Light Theme- In airdrops page, the texts in the middle module are not readable.
![image](https://user-images.githubusercontent.com/88271672/153503774-f8bcd930-b887-4871-8266-4e8afdad6fd0.png)

**Comment by grikomsn** [comment]
Per the Figma design document, we're dropping color modes and will use a single theme. Will keep you posted when it ships.
