### ISSUE TITLE
Got error when instantiating cw20

### ISSUE THREAD

**Issue by bitcoinappdev** [CosmosContracts/juno-tools#175]
At https://juno.tools/contracts/cw20/ when I click "Instantiate Contract"

I got this error message:

`Query failed with (18): failed to execute message; message index: 0: Error parsing into type cw20_base::msg::InstantiateMsg: Invalid type: instantiate wasm contract failed: invalid request`

I was using these values (two screenshots):

![image](https://user-images.githubusercontent.com/17599867/167718185-19790053-08dd-4683-98dc-fc207831b837.png)

![image](https://user-images.githubusercontent.com/17599867/167718337-6a3f645a-5215-417c-a6a7-8e8cc2c5bf34.png)

Minter address in text format in case it's helpful: juno1u5ed7vpt55dedaer2tmw0uxclj08q2z7yznhl9

**Comment by findolor** [comment]
@bitcoinappdev Can you also write the values that you are using?

**Comment by bitcoinappdev** [comment]
Also tried with other values (see screenshot below), no logo, same error message, in Chrome on Windows.

![image](https://user-images.githubusercontent.com/17599867/167719073-c29f3645-b8d9-49b2-9e10-610e8d2da817.png)

**Comment by findolor** [comment]
@bitcoinappdev Thank you for the feedback! I'll take a look at it asap.

**Comment by findolor** [comment]
The problem was the cap field being a number instead of a string. Thanks for creating an issue! Fixed in https://github.com/CosmosContracts/juno-tools/pull/176
