### ISSUE TITLE
For the claim function button of the kingnodes airdrop is not visible or accessible even when i resize screen.  [BUG]

### ISSUE THREAD

**Issue by David-Baxendale** [CosmosContracts/juno-tools#184]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by findolor** [comment]
@David-Baxendale Can you also post a screenshot of the screen?

**Comment by David-Baxendale** [comment]
Sent from Mail for Windows From: Arda NakışçıSent: 14 May 2022 12:19To: CosmosContracts/juno-toolsCc: David-Baxendale; MentionSubject: Re: [CosmosContracts/juno-tools] For the claim function button of the kingnodes airdrop is not visible or accessible even when i resize screen. [BUG] (Issue ***@***.*** Can you also post a screenshot of the screen?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>Hi Arda.Thanks for the reply.This may be a case that I am not eligible for the airdrop. I have tokens delegated and staked with kingnodes.I can’t recall the date when I did this. It maybe possible that it was after the snapshot date. I have closed the query. Apologies for any inconvenience. Thankyou.David
