### ISSUE TITLE
[BUG] Can't use hardware wallet Ledger to claim airdrop

### ISSUE THREAD

**Issue by hpzxk** [CosmosContracts/juno-tools#190]
**Describe the bug**
Use ledger to claim King dao airdrop (https://juno.tools/airdrops/), tap claim airdrop, use ledger to confirm claim, but error msg pop up:
![image](https://user-images.githubusercontent.com/14306177/168481949-96f5cf4f-537f-4ce4-b691-b71090adb0a2.png)

Also can find this msg on mintscan explorer:
failed to execute message; message index: 0: cw_utils::expiration::Expiration not found: execute wasm contract failed

**Comment by findolor** [comment]
Aware of this issue, it's not related to Ledger but something else. Patch will be live tomorrow

**Comment by findolor** [comment]
@hpzxk live in mainnet website
