### ISSUE TITLE
[BUG] Claim button not visible on smaller screen, need to zoom out

### ISSUE THREAD

**Issue by RowanUtrecht** [CosmosContracts/juno-tools#194]
**Describe the bug**
Claim button not visible on smaller screen, need to zoom out

**To Reproduce**
1. Go to Airdrops
2. Zoom 1 (to a small laptop screen)
3. See claim button not being available
4. And no scroll bar being in the screen

**Expected behavior**
Claim button should always be available, or a scroll bar. 
**Screenshots**
![image](https://user-images.githubusercontent.com/87583564/168490173-56e8b5a2-1fb0-4364-a239-bf95d5a026be.png)

**Additional context**

**Comment by findolor** [comment]
@RowanUtrecht this is now live on the mainnet version. Thanks!
