### ISSUE TITLE
[BUG] Send txn on a cw20 has incorrect recipient contract address in JSON msg

### ISSUE THREAD

**Issue by arufaresearch** [CosmosContracts/juno-tools#230]
**Describe the bug**

While doing the `Send` transaction on a cw20, the execute message uses the address of cw20 token as contract recipient instead of what the user has specified leading to failure in the transaction as the `Receive` is called for the cw20 contract and not the actual receiver contract.

**To Reproduce**

1. Go to 'https://juno.tools/contracts/cw20/base/execute/'
2. Add a cw20 contract address
3. Click on 'Send'

**Expected behavior**

The recipient address should be empty when not given by user and should be what user has specified when done instead of cw20 address.

**Screenshots**

<img width="1152" alt="Screenshot 2022-08-10 at 4 06 19 PM" src="https://user-images.githubusercontent.com/106480785/183881580-6a410e2a-c41e-4e20-8290-7c57eb22dcd6.png">

**Additional context**

**Comment by findolor** [comment]
Thanks for letting us know 👍

**Comment by findolor** [comment]
Fixed in https://github.com/CosmosContracts/juno-tools/pull/232
