### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Renzono** [CosmosContracts/juno-tools#243]
**Describe the bug**
no way to start the Airdrop transfer loop tokens to Keplr , with Ledger 
**Screenshots** attached

![erreur-airdrop](https://user-images.githubusercontent.com/43011824/185888011-4d6b8961-0357-4c17-864c-52d326718f22.JPG)

**Comment by findolor** [comment]
@Renzono We are aware of this issue and it is fixed with this https://github.com/CosmosContracts/juno-tools/pull/241

We are also waiting for this https://github.com/CosmWasm/cw-tokens/pull/23 to deploy everything on mainnet.

**Comment by findolor** [comment]
@Renzono Keep in mind that this will not make a difference with Loop airdrop.
They have released a google form for collecting wallet addresses for ledger users. 

If you missed this opportunity, I'm sorry but this fix will not solve your problem. This is a fix for the upcoming terra airdrops.
