### ISSUE TITLE
CLAIMING LOOP airdrop issue[BUG]

### ISSUE THREAD

**Issue by HerisetraBeyond** [CosmosContracts/juno-tools#255]
**Describe the bug**
Not able to claim my LOOP Airdrop. It is stating "Account does not exist on-chain. Send some token there before trying to query sequence"

**To Reproduce**

1. Go to: [juno.tools/airdrops/]
2. Click on 'CONNECT WALLET'
3. Claim Airdrop
4. Inserting Terra Classic address
![JUNO](https://user-images.githubusercontent.com/106643999/188298597-64537a75-63f7-4420-b18c-120b6e06e8a7.PNG)

5. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by findolor** [comment]
@HerisetraBeyond Do you have some tokens in the address that you want to claim with? Before making any action, you need to have some tokens for the blockchain to know your address is there.

**Comment by HerisetraBeyond** [comment]
Got it,

Will add some.jino token there and will check
