### ISSUE TITLE
I can't claim when I have tokens

### ISSUE THREAD

**Issue by Rocky6178** [CosmosContracts/juno-tools#256]
I have 3 claims for airdrops it seems, but I cannot firure out how to acquire them. In the first pic you can see the claims. But when I click on "add token to Kelpr" it doesn't execute or fails. And when I try to claim each token I get a message which you can see in the second pic at the top. How do I claim these tokens?

![JUno tools 1](https://user-images.githubusercontent.com/30920848/188317570-7c76824e-25a2-4a11-bdf4-274ae0230357.jpg)
![Juno tools 2](https://user-images.githubusercontent.com/30920848/188317578-885f95e0-e8fe-4c4c-a7ce-4aa7a09a13f5.jpg)

**Comment by Highlander-maker** [comment]
We will check it out and come back to you. @findolor is the man

**Comment by Rocky6178** [comment]
k

**Comment by findolor** [comment]
@Rocky6178 That message you get means the airdrop is expired and can no longer be claimed by users. It also says in the description.

``Airdrop stage 1 is expired at ...``

**Comment by Rocky6178** [comment]
Hello? Can anybody help?

**Comment by Rocky6178** [comment]
Thanks Findolor, will look closer next time.
