### ISSUE TITLE
BKHL Airdrop not working

### ISSUE THREAD

**Issue by Threevus** [CosmosContracts/juno-tools#257]
**Describe the bug**
Hi I am needing help with my BKHL airdrop. I should be receiving 800 BKHL. It has never worked. BKHL is in my Juno drop lost, but I cannot receive the airdrop. HOLE has been received with no problem, but BKHL does not work

**To Reproduce**
Claim Airdrop button returns an error message on the JunoTools website.

**Expected behavior**
BKHL to be airdropped into my Juno wallet address
juno10ue6namsx5al7u8nuxe4ut7hrsflpkj5mc5pkd

**Screenshots**
<img width="1629" alt="Screen Shot 2022-09-10 at 2 27 08 PM" src="https://user-images.githubusercontent.com/113266184/189503593-d87b0929-361f-4c89-9142-4dad62784a93.png">

**Additional context**
HOLE airdrop worked without a problem
BKHL has not been working for weeks

**Comment by findolor** [comment]
@Threevus This airdrop has no balance, that's why you are getting this error.

**Comment by Threevus** [comment]
But it also says that I should be airdropped 800 BKHL… am I wrong?

**Comment by findolor** [comment]
@Threevus This is not related to JunoTools since the airdrop creator must add funds to the contract but they didn't.
