### ISSUE TITLE
Prevent scrolling in sidebar

### ISSUE THREAD

**Issue by RyanWarner** [CosmosContracts/juno-tools#31]
I see scrollbars on my local. We should update the CSS to prevent the need for scrolling the sidebar.

<img width="1556" alt="Screen Shot 2022-02-14 at 8 13 59 PM" src="https://user-images.githubusercontent.com/1595979/153973837-e7d7a10f-65ad-4999-8f97-9c52b75bb913.png">

**Comment by grikomsn** [comment]
So the scroll follows the viewport instead of itself?
