### ISSUE TITLE
RFC: Form handling using react-hook-form

### ISSUE THREAD

**Issue by grikomsn** [CosmosContracts/juno-tools#46]
Current form implementations throughout the app does not use any form handling library. This RFC issue highlights on using react-hook-form for handling form fields.

## Reason

While using regular forms (or just basic input controls) works as is, it adds overhead when needing to handle additional fields or having input validations. Using a form handling library will help abstracting logics better to determine what fields and which is valid without having to jump hoops on several `useState`s and other quirks.

## Pros

- less controlled states (no `useState`s for each field)
- easier and robust field validation (use prebuild validators or add your own)
- fields definition colocation (typed field datas)
- GUI-based form builder to generate form code (https://www.react-hook-form.com/form-builder)

## Cons

- package dependency overhead
- uncontrolled fields (react-hook-form only attaches to field refs)
- ...

## References

- https://www.react-hook-form.com
- https://www.react-hook-form.com/get-started
- https://www.react-hook-form.com/form-builder

cc @RyanWarner @XanderJL @findolor @Highlander-maker

**Comment by XanderJL** [comment]
+1 for react-hook-form

**Comment by findolor** [comment]
I'm also down for the react-hook-form 👍
