### ISSUE TITLE
Split airdrop escrow step as separate page

### ISSUE THREAD

**Issue by grikomsn** [CosmosContracts/juno-tools#58]
Current airdrop escrow step is combined in `/airdrops/register` page. This issue highlights on the idea of extracting the escrow step as a separate page (e.g., `/airdrops/escrow`).

## Reason

Current implementation for escrowing is shown in `/airdrops/register` after creating an airdrop, where after depositing it'll show the register form.

Related with #50 which if its implemented, users can navigate through each step which per step has its own page:

- `/airdrops/create`
- `/airdrops/escrow`
- `/airdrops/register`
- `/airdrops/fund`

**Comment by findolor** [comment]
I think having escrow page separated like in the designs is much better than having component in both register and fund.

If we detect the escrow in register and fund pages, we could easily redirect the user to the dedicated page.
